def show_menu():
    print("/n=====Algorithm Bot Menu=====")
    print("1.Singly linked list")
    print("2.Pythagorean fractal")
    print("3.Dijkstra's algorithm")
    print("4.Heap visualization")
    print("5.Visualization of binary tree traversal")
    print("6.Calories (Greedy vs DP)")
    print("7.Monte Carlo (cubes)")
    print("8.Exit")